version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://dakshkansal03:OqJsLTXuHAYy4iOX@cluster0.1r9u5xl.mongodb.net/ecommerce?retryWrites=true&w=majority
      - JWT_SECRET=287d1e408ba65eeed0b71db57f88af4f80619f9a789e4e6b2a7c8b3416835aae2aec4f9fa8de26334ac071d8da1b99d7280527b1e37fc0c411b5c5a32da41076
    depends_on:
      - frontend  # optional — backend might not need frontend

  frontend:
    build:
      context: .
    ports:
      - "3000:80"
    depends_on:
      - backend

